//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onixa.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsImageName
    {
        public int ID { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public string Path { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
